version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
